name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn build
      env:
        NODE_ENV: production
        CI: true
    - run: yarn test
      env:
        NODE_ENV: test
        CI: true
    - name: rsync deploy
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr
        path: static/
        remote_path: /opt/pleroma/lib/pleroma-2.1.0/priv/static
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
